#!/usr/bin/env node
// Copies Letter Garden from its development checkout into garden/ so it is served
// at qandeel.app/garden/. Only the files the game actually uses are copied:
// everything letters.html links, the fonts, the letter audio and the eleven
// short-surah data files. The service worker is regenerated with a shell list
// that matches exactly what was copied (cache.addAll fails on any 404).
//
//   node scripts/sync-garden.mjs [path-to-letter-garden-checkout]
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const site = path.resolve(here, "..");
const src = path.resolve(process.argv[2] || path.join(process.env.HOME, "Documents/GitHub/miftah/.local-work/letter-garden-next-major"));
const dest = path.join(site, "garden");
const SURAHS = [1, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114];

if (!fs.existsSync(path.join(src, "letters.html"))) {
  console.error(`No letters.html in ${src}`);
  process.exit(1);
}

fs.rmSync(dest, { recursive: true, force: true });
const copied = new Set();
function copy(rel) {
  const from = path.join(src, rel);
  if (!fs.existsSync(from)) throw new Error(`missing in source: ${rel}`);
  const to = path.join(dest, rel);
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
  copied.add(rel);
}
function copyDir(rel) {
  for (const entry of fs.readdirSync(path.join(src, rel), { withFileTypes: true })) {
    if (entry.name.startsWith(".")) continue;
    const child = path.posix.join(rel, entry.name);
    entry.isDirectory() ? copyDir(child) : copy(child);
  }
}

// 1. The page and everything it links locally.
let html = fs.readFileSync(path.join(src, "letters.html"), "utf8");
const linked = [...html.matchAll(/(?:src|href)="([^"#?]+)(?:\?[^"]*)?"/g)]
  .map((m) => m[1])
  .filter((p) => !/^(https?:|data:|mailto:)/.test(p));
for (const rel of new Set(linked)) copy(rel);

// 2. Runtime assets: fonts (fonts.css points at sibling files), letter audio, surah data.
copyDir("vendor/fonts");
copyDir("assets/audio/letters");
for (const n of SURAHS) copy(`data/surah-${n}.json`);

// 3. The page itself, pointed at qandeel.app.
html = html
  .replace(/data-domain="[^"]*"/, 'data-domain="qandeel.app"')
  .replace(/<title>[^<]*<\/title>/, "<title>Letter Garden · حديقة الحروف · Qandeel</title>")
  .replace(/(property="og:title" content=")[^"]*"/, '$1Letter Garden · Qandeel"');
fs.writeFileSync(path.join(dest, "index.html"), html);

// 4. A service worker for exactly these files.
const sw = fs.readFileSync(path.join(src, "sw.js"), "utf8");
const version = (sw.match(/const VERSION = "([^"]+)"/) || [])[1] || "unknown";
const shell = ["./", "index.html", ...[...copied].filter((p) => !p.startsWith("data/") && !p.startsWith("assets/audio/")).sort()];
const data = SURAHS.map((n) => `data/surah-${n}.json`);
let out = sw
  .replace(/const VERSION = "[^"]+";/, `const VERSION = "qandeel-garden-${version}";`)
  .replace(/const SHELL = \[[\s\S]*?\];/, `const SHELL = ${JSON.stringify(shell, null, 2)};`)
  .replace(/const DATA = \[[\s\S]*?\];/, `const DATA = ${JSON.stringify(data, null, 2)};`)
  .replace("// Miftah service worker", "// Letter Garden service worker (generated by scripts/sync-garden.mjs from the Miftah worker)");
fs.writeFileSync(path.join(dest, "sw.js"), out);

const bytes = [...copied].reduce((n, rel) => n + fs.statSync(path.join(dest, rel)).size, 0);
console.log(`garden/: ${copied.size + 2} files, ${(bytes / 1048576).toFixed(1)} MB, shell ${shell.length}, sw ${version}`);
